-- diff view for git merge conflicts
return {
  "sindrets/diffview.nvim",
  keys = {
    { "<leader>gvd", "<cmd>DiffviewOpen<cr>", desc = "Diffview Open" },
    { "<leader>gvD", "<cmd>DiffviewClose<cr>", desc = "Diffview Close" },
    { "<leader>gvh", "<cmd>DiffviewFileHistory %<cr>", desc = "File History (current file)" },
    { "<leader>gvH", "<cmd>DiffviewFileHistory<cr>", desc = "File History (current branch)" },
  },

  config = function()
    require("diffview").setup({
      keymaps = {
        disable_defaults = true, -- Disable the default keymaps
        view = {
          { "n", "<tab>", require("diffview.actions").select_next_entry, { desc = "Open diff for next file" } },
          { "n", "<s-tab>", require("diffview.actions").select_prev_entry, { desc = "Open diff for previous file" } },
          { "n", "[F", require("diffview.actions").select_first_entry, { desc = "Open diff for first file" } },
          { "n", "]F", require("diffview.actions").select_last_entry, { desc = "Open diff for last file" } },
          { "n", "gf", require("diffview.actions").goto_file_edit, { desc = "Open file in previous tabpage" } },
          { "n", "<C-w><C-f>", require("diffview.actions").goto_file_split, { desc = "Open file in new split" } },
          { "n", "<C-w>gf", require("diffview.actions").goto_file_tab, { desc = "Open the file in new tabpage" } },
          { "n", "<leader>e", require("diffview.actions").focus_files, { desc = "Bring focus to file panel" } },
          { "n", "<leader>b", require("diffview.actions").toggle_files, { desc = "Toggle file panel" } },
          { "n", "g<C-x>", require("diffview.actions").cycle_layout, { desc = "Cycle through available layouts" } },
          { "n", "[x", require("diffview.actions").prev_conflict, { desc = "merge-tool: previous conflict" } },
          { "n", "]x", require("diffview.actions").next_conflict, { desc = "merge-tool: next conflict" } },
          {
            "n",
            "<leader>gvo",
            require("diffview.actions").conflict_choose("ours"),
            { desc = "Choose ours (hunk)" },
          },
          {
            "n",
            "<leader>gvt",
            require("diffview.actions").conflict_choose("theirs"),
            { desc = "Choose theirs (hunk)" },
          },
          {
            "n",
            "<leader>gvb",
            require("diffview.actions").conflict_choose("base"),
            { desc = "Choose base (hunk)" },
          },
          { "n", "<leader>gva", require("diffview.actions").conflict_choose("all"), { desc = "Choose both (hunk)" } },
          {
            "n",
            "<leader>gvn",
            require("diffview.actions").conflict_choose("none"),
            { desc = "Delete conflict (hunk)" },
          },
          {
            "n",
            "<leader>gvO",
            require("diffview.actions").conflict_choose_all("ours"),
            { desc = "Choose ours (file)" },
          },
          {
            "n",
            "<leader>gvT",
            require("diffview.actions").conflict_choose_all("theirs"),
            { desc = "Choose theirs (file)" },
          },
          {
            "n",
            "<leader>gvB",
            require("diffview.actions").conflict_choose_all("base"),
            { desc = "Choose base (file)" },
          },
          {
            "n",
            "<leader>gvA",
            require("diffview.actions").conflict_choose_all("all"),
            { desc = "Choose both (file)" },
          },
          {
            "n",
            "<leader>gvN",
            require("diffview.actions").conflict_choose_all("none"),
            { desc = "Delete conflict (file)" },
          },
        },
        diff1 = {
          { "n", "g?", require("diffview.actions").help({ "view", "diff1" }), { desc = "Open help panel" } },
        },
        diff2 = {
          { "n", "g?", require("diffview.actions").help({ "view", "diff2" }), { desc = "Open help panel" } },
        },
        diff3 = {
          { { "n", "x" }, "2do", require("diffview.actions").diffget("ours"), { desc = "Choose ours" } },
          { { "n", "x" }, "3do", require("diffview.actions").diffget("theirs"), { desc = "Choose theirs" } },
          { "n", "g?", require("diffview.actions").help({ "view", "diff3" }), { desc = "Open help panel" } },
        },
        diff4 = {
          { { "n", "x" }, "1do", require("diffview.actions").diffget("base"), { desc = "Choose base" } },
          { { "n", "x" }, "2do", require("diffview.actions").diffget("ours"), { desc = "Choose ours" } },
          { { "n", "x" }, "3do", require("diffview.actions").diffget("theirs"), { desc = "Choose theirs" } },
          { "n", "g?", require("diffview.actions").help({ "view", "diff4" }), { desc = "Open help panel" } },
        },
        file_panel = {
          { "n", "j", require("diffview.actions").next_entry, { desc = "next file entry" } },
          { "n", "<down>", require("diffview.actions").next_entry, { desc = "next file entry" } },
          { "n", "k", require("diffview.actions").prev_entry, { desc = "previous file entry" } },
          { "n", "<up>", require("diffview.actions").prev_entry, { desc = "previous file entry" } },
          { "n", "<cr>", require("diffview.actions").select_entry, { desc = "Open diff for selected" } },
          { "n", "o", require("diffview.actions").select_entry, { desc = "Open diff for selected" } },
          { "n", "l", require("diffview.actions").select_entry, { desc = "Open diff for selected" } },
          { "n", "<2-LeftMouse>", require("diffview.actions").select_entry, { desc = "Open diff for selected" } },
          { "n", "-", require("diffview.actions").toggle_stage_entry, { desc = "Stage / unstage selected" } },
          { "n", "s", require("diffview.actions").toggle_stage_entry, { desc = "Stage / unstage selected" } },
          { "n", "S", require("diffview.actions").stage_all, { desc = "Stage all entries" } },
          { "n", "U", require("diffview.actions").unstage_all, { desc = "Unstage all entries" } },
          { "n", "X", require("diffview.actions").restore_entry, { desc = "Restore entry to state on left side" } },
          { "n", "L", require("diffview.actions").open_commit_log, { desc = "Open commit log panel" } },
          { "n", "zo", require("diffview.actions").open_fold, { desc = "Expand fold" } },
          { "n", "h", require("diffview.actions").close_fold, { desc = "Collapse fold" } },
          { "n", "zc", require("diffview.actions").close_fold, { desc = "Collapse fold" } },
          { "n", "za", require("diffview.actions").toggle_fold, { desc = "Toggle fold" } },
          { "n", "zR", require("diffview.actions").open_all_folds, { desc = "Expand all folds" } },
          { "n", "zM", require("diffview.actions").close_all_folds, { desc = "Collapse all folds" } },
          { "n", "<c-b>", require("diffview.actions").scroll_view(-0.25), { desc = "Scroll view up" } },
          { "n", "<c-f>", require("diffview.actions").scroll_view(0.25), { desc = "Scroll view down" } },
          { "n", "<tab>", require("diffview.actions").select_next_entry, { desc = "Open diff for next file" } },
          { "n", "<s-tab>", require("diffview.actions").select_prev_entry, { desc = "Open diff for previous file" } },
          { "n", "[F", require("diffview.actions").select_first_entry, { desc = "Open diff for first file" } },
          { "n", "]F", require("diffview.actions").select_last_entry, { desc = "Open diff for last file" } },
          { "n", "gf", require("diffview.actions").goto_file_edit, { desc = "Open file in previous tabpage" } },
          { "n", "<C-w><C-f>", require("diffview.actions").goto_file_split, { desc = "Open file in new split" } },
          { "n", "<C-w>gf", require("diffview.actions").goto_file_tab, { desc = "Open file in new tabpage" } },
          {
            "n",
            "i",
            require("diffview.actions").listing_style,
            { desc = "Toggle between 'list' and 'tree' views" },
          },
          {
            "n",
            "f",
            require("diffview.actions").toggle_flatten_dirs,
            { desc = "Flatten empty subdirectories in tree listing style" },
          },
          {
            "n",
            "R",
            require("diffview.actions").refresh_files,
            { desc = "Update stats and entries in file list" },
          },
          { "n", "<leader>e", require("diffview.actions").focus_files, { desc = "Bring focus to file panel" } },
          { "n", "<leader>b", require("diffview.actions").toggle_files, { desc = "Toggle file panel" } },
          { "n", "g<C-x>", require("diffview.actions").cycle_layout, { desc = "Cycle available layouts" } },
          { "n", "[x", require("diffview.actions").prev_conflict, { desc = "Go to previous conflict" } },
          { "n", "]x", require("diffview.actions").next_conflict, { desc = "Go to next conflict" } },
          { "n", "g?", require("diffview.actions").help("file_panel"), { desc = "Open help panel" } },
          {
            "n",
            "<leader>gvO",
            require("diffview.actions").conflict_choose_all("ours"),
            { desc = "Choose ours (file)" },
          },
          {
            "n",
            "<leader>gvT",
            require("diffview.actions").conflict_choose_all("theirs"),
            { desc = "Choose theirs (file)" },
          },
          {
            "n",
            "<leader>gvB",
            require("diffview.actions").conflict_choose_all("base"),
            { desc = "Choose base (file)" },
          },
          {
            "n",
            "<leader>gvA",
            require("diffview.actions").conflict_choose_all("all"),
            { desc = "Choose both (file)" },
          },
          {
            "n",
            "<leader>gvN",
            require("diffview.actions").conflict_choose_all("none"),
            { desc = "Delete conflict (file)" },
          },
        },
        file_history_panel = {
          { "n", "g!", require("diffview.actions").options, { desc = "Open option panel" } },
          {
            "n",
            "<C-A-d>",
            require("diffview.actions").open_in_diffview,
            { desc = "Open entry under cursor in a diffview" },
          },
          { "n", "y", require("diffview.actions").copy_hash, { desc = "Copy commit hash of entry under cursor" } },
          { "n", "L", require("diffview.actions").open_commit_log, { desc = "Show commit details" } },
          {
            "n",
            "X",
            require("diffview.actions").restore_entry,
            { desc = "Restore file to state from selected entry" },
          },
          { "n", "zo", require("diffview.actions").open_fold, { desc = "Expand fold" } },
          { "n", "zc", require("diffview.actions").close_fold, { desc = "Collapse fold" } },
          { "n", "h", require("diffview.actions").close_fold, { desc = "Collapse fold" } },
          { "n", "za", require("diffview.actions").toggle_fold, { desc = "Toggle fold" } },
          { "n", "zR", require("diffview.actions").open_all_folds, { desc = "Expand all folds" } },
          { "n", "zM", require("diffview.actions").close_all_folds, { desc = "Collapse all folds" } },
          { "n", "j", require("diffview.actions").next_entry, { desc = "Bring cursor to next file entry" } },
          { "n", "<down>", require("diffview.actions").next_entry, { desc = "Bring cursor to next file entry" } },
          { "n", "k", require("diffview.actions").prev_entry, { desc = "Bring cursor to previous file entry" } },
          { "n", "<up>", require("diffview.actions").prev_entry, { desc = "Bring cursor to previous file entry" } },
          { "n", "<cr>", require("diffview.actions").select_entry, { desc = "Open diff for selected entry" } },
          { "n", "o", require("diffview.actions").select_entry, { desc = "Open diff for selected entry" } },
          { "n", "l", require("diffview.actions").select_entry, { desc = "Open diff for selected entry" } },
          {
            "n",
            "<2-LeftMouse>",
            require("diffview.actions").select_entry,
            { desc = "Open diff for selected entry" },
          },
          { "n", "<c-b>", require("diffview.actions").scroll_view(-0.25), { desc = "Scroll view up" } },
          { "n", "<c-f>", require("diffview.actions").scroll_view(0.25), { desc = "Scroll view down" } },
          { "n", "<tab>", require("diffview.actions").select_next_entry, { desc = "Open diff for next file" } },
          {
            "n",
            "<s-tab>",
            require("diffview.actions").select_prev_entry,
            { desc = "Open diff for previous file" },
          },
          { "n", "[F", require("diffview.actions").select_first_entry, { desc = "Open diff for first file" } },
          { "n", "]F", require("diffview.actions").select_last_entry, { desc = "Open diff for last file" } },
          { "n", "gf", require("diffview.actions").goto_file_edit, { desc = "Open file in previous tabpage" } },
          { "n", "<C-w><C-f>", require("diffview.actions").goto_file_split, { desc = "Open file in new split" } },
          { "n", "<C-w>gf", require("diffview.actions").goto_file_tab, { desc = "Open file in new tabpage" } },
          { "n", "<leader>e", require("diffview.actions").focus_files, { desc = "Bring focus to file panel" } },
          { "n", "<leader>b", require("diffview.actions").toggle_files, { desc = "Toggle file panel" } },
          { "n", "g<C-x>", require("diffview.actions").cycle_layout, { desc = "Cycle available layouts" } },
          { "n", "g?", require("diffview.actions").help("file_history_panel"), { desc = "Open help panel" } },
        },
        option_panel = {
          { "n", "<tab>", require("diffview.actions").select_entry, { desc = "Change current option" } },
          { "n", "q", require("diffview.actions").close, { desc = "Close panel" } },
          { "n", "g?", require("diffview.actions").help("option_panel"), { desc = "Open help panel" } },
        },
        help_panel = {
          { "n", "q", require("diffview.actions").close, { desc = "Close help menu" } },
          { "n", "<esc>", require("diffview.actions").close, { desc = "Close help menu" } },
        },
      },
    })
  end,
}
