# Prefix Ctrl-s
set -g prefix C-s
unbind C-b
bind C-s send-prefix

# Start window/pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows automatically
set -g renumber-windows on

# Enable mouse
set -g mouse on

# Use vi keys in copy mode
setw -g mode-keys vi

# 256 colors
set -g default-terminal "tmux-256color"

# Reload configuration
unbind r
bind r source-file ~/.config/tmux/.tmux.conf \; display-message "Config reloaded"


# Vim style pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Splitting
bind | split-window -h
bind - split-window -v

# New panes start in the current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'alexwforsythe/tmux-which-key'

set -g @continuum-boot 'on'
set -g @continuum-boot-options 'iterm'
set -g @continuum-restore 'on'

set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g status-position top
set -g @dracula-plugins "cwd weather cpu-usage gpu-usage ram-usage"
set -g @dracula-show-empty-plugins false
set -g @dracula-cpu-usage-label " "
set -g @dracula-gpu-power-label "󰢮 "
set -g @dracula-gpu-usage-label "󰢮 "
set -g @dracula-gpu-vram-label "󰢮 "
set -g @dracula-ram-usage-label " "
set -g @dracula-cwd-colors "light_purple dark_gray"
set -g @dracula-cpu-usage-colors "white dark_gray"
set -g @dracula-show-location false
set -g @dracula-show-fahrenheit false
set -g @dracula-weather-unit 'c'

# Initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
